name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'  # Adjust the Java version as needed

    - name: Build and Generate Javadoc
      run: ./gradlew javadoc

    - name: Deploy Javadoc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/javadoc
